export const ISTEAMUSERSTATS_GETUSERSTATSFORGAME_LIST_FETCHING =
    'ISTEAMUSERSTATS_GETUSERSTATSFORGAME_LIST_FETCHING';

export const STATS_UPDATE_STAT = 'STATS_UPDATE_STAT';
export const STATS_UPDATE_LIST_OFFSET = 'STATS_UPDATE_LIST_OFFSET';
export const STATS_SET_FETCHING = 'STATS_SET_FETCHING';
export const STATS_UPDATE_LIST = 'STATS_UPDATE_LIST';

